# Data Visualization and the Grammar of Graphics

In [2]:
import pandas as pd

import altair as alt

import plotly.express as px

In [3]:
df_ames = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/AmesHousing.txt", sep="\t")
df_ames

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [4]:
df_covid = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/covid_PT_CO_2020-05-28.csv")
df_covid

      country  fatality    age
0          PT         0  60-69
1          PT         0  60-69
2          PT         0    80+
3          PT         0  60-69
4          PT         0  50-59
...       ...       ...    ...
56957      CO         0  40-49
56958      CO         0  50-59
56959      CO         0  30-39
56960      CO         0  10-19
56961      CO         0    0-9

[56962 rows x 3 columns]

In [5]:
df_titanic = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv")
df_titanic

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2202,"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,1,NaN,deck crew
2203,"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,1,NaN,victualling crew
2204,"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew
2205,"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff
2206,"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff

In [6]:
df_penguins = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/penguins.csv")

df_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

## Recreations

Use Plotly or Altair to recreate some of the graphics we have already produced using Pandas

The colored scatterplot from the penguins data

In [7]:
alt.Chart(df_penguins).mark_point().encode(
    x="bill_length_mm",
    y="bill_depth_mm",
    color="species"
)

alt.Chart(...)

The faceted scatterplot from the penguins data

In [8]:
alt.Chart(df_penguins).mark_point().encode(
    x="bill_length_mm",
    y="bill_depth_mm",
    facet="species"
)

alt.Chart(...)

The side-by-side bar plot from the COVID data

In [9]:
df_country = df_covid.groupby(["country", "age"])["fatality"].mean().reset_index()

# Altair Version 5
alt.Chart(df_country).mark_bar().encode(
    x="age",
    y="fatality",
    color="country",
    xOffset="country"
)

# Altair Version 4
# alt.Chart(df_country).mark_bar().encode(
#     x="country",
#     y='fatality',
#     color="country",
#     column="age"
# )

alt.Chart(...)

The overlaid histograms (or density plots) of sale price by building type for the Ames housing data

In [10]:
# overlaid histograms in altair
# alt.Chart(df_ames).mark_bar().encode(
#     x="SalePrice",
#     y="count()"
# )
# df_ames.columns
df_building = df_ames.groupby(["Bldg Type"])["SalePrice"].value_counts().reset_index(name="count")
df_building

alt.Chart(df_building).transform_fold( 
    ['Bldg Type'], 
    as_=['Columns', 'Values'] 
).mark_area( 
    opacity=0.5, 
    interpolate='step'
).encode( 
    alt.X('SalePrice', bin=alt.Bin(maxbins=100)), 
    alt.Y('count(SalePrice)'), 
    alt.Color('Bldg Type:N')
)

alt.Chart(...)

## Graph Gallery

Look at the examples in the [Altair Graph Gallery](https://altair-viz.github.io/gallery/index.html) or the [Plotly Graph Gallery](https://plotly.com/python/plotly-express/#gallery). Think about the data sets we have seen so far; what graphs might provide good visualizations in these contexts? Then try to apply some of the principles/examples from the graph gallery to the data sets we have seen already. (You're also welcome to bring your own data set!)

The main purpose here is to experiment and get practice with producing graphs. But do also think about the story the graph tells. Just because you can produce a graph doesn't necessarily mean it's an effective visual in context. Try to select graphs that most effectively convey the story in the data.

In [11]:
df_class = df_titanic.groupby(["class"])["survived"].value_counts()
df_class

class             survived
1st               1           201
                  0           123
2nd               0           166
                  1           118
3rd               0           528
                  1           181
deck crew         1            43
                  0            23
engineering crew  0           253
                  1            71
restaurant staff  0            66
                  1             3
victualling crew  0           337
                  1            94
Name: count, dtype: int64

In [12]:
alt.Chart(df_titanic).mark_arc(innerRadius=50).encode(
    theta="sum(survived)",
    color="class:N",
)

alt.Chart(...)

## Copy the Masters

(This activity was written by [Dr. Emily Robinson](https://earobinson95.github.io/stat365-calpoly/97-mini-projects/copy-the-masters/copy-the-masters.html) at Cal Poly.)

In this section you will try to recreate graphics produced by FiveThirtyEight. Start at the [Our Data](https://data.fivethirtyeight.com/) page and find a graphic that interests you and you think is possible to reproduce. Then try to reproduce it! It doesn't have to be an exact match, but try to get as close as you can.

Don't try to do everything at once. Think in terms of several drafts: the first draft should just have the basic structure (e.g., bar chart, scatterplot, histogram), the second graph can add features like color, the third draft can add titles/labels, etc. Create your drafts in several code cells. For example, put your first draft in one cell and run it, then copy that code to a second cell and revise to add more features. You should be able to see the progression of your graph across the several drafts, and not just the end result.

Here are a few you might consider

- The House and Senate are older than ever before, from [Congress Today Is Older Than It's Ever Been](https://fivethirtyeight.com/features/aging-congress-boomers/) (or some of the other graphs in the article)
- Cleveland's settlement amounts rose after Rice's death, from [Cities Spend Millions On Police Misconduct Every Year. Here's Why It's So Difficult to Hold Departments Accountable](https://fivethirtyeight.com/features/police-misconduct-costs-cities-millions-every-year-but-thats-where-the-accountability-ends/)
- More players transfer to the US than to any other country from [American Chess Is Great Again](https://fivethirtyeight.com/features/american-chess-is-great-again/)
- Hurricane Maria and Puerto Rico got comparatively little online coverage, from [The Media Really Has Neglected Puerto Rico](https://fivethirtyeight.com/features/the-media-really-has-neglected-puerto-rico/) (other graphs in the article look doable, too)
- Do you think that society puts pressure on men in a way that is unhealthy or bad for them?, from [What Do Men Think It Means To Be A Man?](https://fivethirtyeight.com/features/what-do-men-think-it-means-to-be-a-man/) (other graphs in the article look doable, too)
- Trump is less popular than leading Democratic candidates, from The [Democratic Presidential Candidates Are Becoming Less Popular](https://fivethirtyeight.com/features/the-democratic-presidential-candidates-are-becoming-less-popular/)

In [14]:
df_men = pd.read_csv("./raw-responses.csv")

,Unnamed: 0,StartDate,EndDate,q0001,q0002,q0004_0001,q0004_0002,q0004_0003,q0004_0004,q0004_0005,...,q0035,q0036,race2,racethn4,educ3,educ4,age3,kids,orientation,weight
0,1,5/10/18 4:01,5/10/18 4:06,Somewhat masculine,Somewhat important,Not selected,Not selected,Not selected,Pop culture,Not selected,...,Middle Atlantic,Windows Desktop / Laptop,Non-white,Hispanic,College or more,College or more,35 - 64,No children,Gay/Bisexual,1.714026
1,2,5/10/18 6:30,5/10/18 6:53,Somewhat masculine,Somewhat important,Father or father figure(s),Not selected,Not selected,Not selected,Not selected,...,East North Central,iOS Phone / Tablet,White,White,Some college,Some college,65 and up,Has children,Straight,1.247120
2,3,5/10/18 7:02,5/10/18 7:09,Very masculine,Not too important,Father or father figure(s),Not selected,Not selected,Not selected,Not selected,...,East North Central,Windows Desktop / Laptop,White,White,College or more,College or more,35 - 64,Has children,Straight,0.515746
3,4,5/10/18 7:27,5/10/18 7:31,Very masculine,Not too important,Father or father figure(s),Mother or mother figure(s),Other family members,Not selected,Not selected,...,East North Central,Windows Desktop / Laptop,White,White,Some college,Some college,65 and up,Has children,No answer,0.600640
4,5,5/10/18 7:35,5/10/18 7:42,Very masculine,Very important,Not selected,Not selected,Other family members,Not selected,Not selected,...,East North Central,Windows Desktop / Laptop,White,White,College or more,College or more,35 - 64,No children,Straight,1.033400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1610,1611,5/22/18 8:48,5/22/18 8:52,Not very masculine,Not at all important,Father or father figure(s),Mother or mother figure(s),Other family members,Pop culture,Friends,...,West North Central,iOS Phone / Tablet,White,White,Some college,Some college,18 - 34,No children,Straight,2.891038
1611,1612,5/22/18 9:15,5/22/18 9:24,Very masculine,Very important,Father or father figure(s),Not selected,Other family members,Not selected,Not selected,...,NaN,iOS Phone / Tablet,Non-white,Hispanic,High school or less,High school or less,35 - 64,Has children,Straight,8.643674
1612,1613,5/22/18 9:22,5/22/18 9:39,Somewhat masculine,Somewhat important,Not selected,Mother or mother figure(s),Not selected,Not selected,Not selected,...,South Atlantic,Windows Desktop / Laptop,White,White,Some college,Some college,35 - 64,Has children,Straight,2.340241
1613,1614,5/22/18 9:44,5/22/18 9:50,Somewhat masculine,Somewhat important,Not selected,Mother or mother figure(s),Not selected,Not selected,Not selected,...,Mountain,Windows Desktop / Laptop,White,White,High school or less,High school or less,18 - 34,No children,Straight,6.557984
1614,1615,5/22/18 9:55,5/22/18 10:00,Very masculine,Not at all important,Father or father figure(s),Mother or mother figure(s),Not selected,Not selected,Not selected,...,Middle Atlantic,iOS Phone / Tablet,White,White,Some college,Some college,18 - 34,No children,Straight,2.817560

In [28]:
df_masc = df_men.groupby(["age3"])["q0001"].value_counts().reset_index()
df_masc

         age3                 q0001  count
0     18 - 34    Somewhat masculine     62
1     18 - 34        Very masculine     45
2     18 - 34    Not very masculine     17
3     18 - 34  Not at all masculine      9
4     35 - 64    Somewhat masculine    445
5     35 - 64        Very masculine    322
6     35 - 64    Not very masculine     66
7     35 - 64  Not at all masculine     13
8     35 - 64             No answer      9
9   65 and up    Somewhat masculine    319
10  65 and up        Very masculine    245
11  65 and up    Not very masculine     48
12  65 and up  Not at all masculine     10
13  65 and up             No answer      5

In [29]:
alt.Chart(df_masc).mark_bar().encode(
    x="age3",
    y="count",
    color="q0001",
    xOffset="q0001"
)

alt.Chart(...)